# Generated by Django 4.2.5 on 2023-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='other',
            field=models.ImageField(default='', upload_to='post'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
